version: '3.8'

services:
      mysql:
        image: mysql:latest
        container_name: mysqlDB
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - "3306:3306"
        command:
          - "mysqld"
          - "--init-file=/docker-entrypoint-initdb.d/init.sql"
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       
      mariadb:
        image: mariadb
        container_name: mariaDB
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: secret
        ports:
          - "3307:3306"
        command:
          - "--init-file=/docker-entrypoint-initdb.d/init.sql"
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
